services:
  # API server
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3050:3000'
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - nest-winston-morgan

  # # mongo database
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - mongodb_data:/data/db
    networks:
      - nest-winston-morgan

  # Mongo express for data visualization
  mongoexpress:
    image: mongo-express
    container_name: mongoexpress
    restart: always
    ports:
      - '8079:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_OPTIONS_EDITORTHEME: blackboard
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - nest-winston-morgan

networks:
  nest-winston-morgan:
    driver: bridge

volumes:
  mongodb_data:
